### PR TITLE
Add support for PostgreSQL v12

### PR DESCRIPTION
**Pull request by gleu**
Few changes to compile and use pg_filedump with PostgreSQL 12

### CODE REVIEW

**Comment by ololobus** [comment]
Hi @gleu, this is really cool that you submitted your PR, since I'm playing around with v12 support right now :)

I found that you removed `pg_lzcompress.c` from `Makefile`. But it seems that `pg_filedump` was using `#include <common/pg_lzcompress.h>` for a while, so actually it never used locally compiled version of `pg_lzcompress.c`, didn't it? Thus, can we safely remove `pg_lzcompress.c` from the repo?

Also, since `pg_filedump` matches version-to-version with Postgres, probably you have to bump `FD_VERSION` to `12.0` in your PR?

**Comment by gleu** [comment]
I don't know if the local pg_lzcompress.c was ever used. What I do know though is that it's no used right now, and having it makes pg_filedump not compilable. So I removed it from the Makefile to make sure I can compile pg_filedump. I suppose we could remove pg_lzcompress.c entirely, but I'll let that decision to the repository's owner.

On bumping FD_VERSION, I'm not sure if anything more needs to be done. All I did is making sure that pg_filedump could be compiled against PostgreSQL 12. I used it a bit and it seems to work nicely. But still, not sure nothing else needs to be done. So I decided to let the repository's owner the time to bump it when it's needed.

**Comment by df7cb** [comment]
I just put pg_filedump on travis-ci and the answer seems to be that the file was added because older versions (<= 9.4) didn't have the header, at least not in that location. I'll do some more digging tomorrow.

https://travis-ci.org/df7cb/pg_filedump/builds/617753475

Thanks for the PR!

**Comment by df7cb** [comment]
Thanks for the patch, committed as c2fb5f790a5fb84.

**Comment by df7cb** [comment]
@ololobus: Anything you want to add before we release 12.0?

**Comment by df7cb** [comment]
(Notably, I added a testsuite now)

**Comment by ololobus** [comment]
@df7cb everything looks fine now from my perspective, since we do not support <=9.4. Thanks!

**Comment by df7cb** [comment]
Aye, put the release up now.

**Pull request closed without merging**
